export const UPDATE_PLAYER_ONE_NAME = "UPDATE_PLAYER_ONE_NAME";
export const UPDATE_PLAYER_TWO_NAME = "UPDATE_PLAYER_TWO_NAME";
export const UPDATE_PLAYER_ONE_COLOR = "UPDATE_PLAYER_ONE_COLOR";
export const UPDATE_PLAYER_TWO_COLOR = "UPDATE_PLAYER_TWO_COLOR";

export default {
  UPDATE_PLAYER_ONE_NAME,
  UPDATE_PLAYER_TWO_NAME,
  UPDATE_PLAYER_ONE_COLOR,
  UPDATE_PLAYER_TWO_COLOR
};
